### ISSUE TITLE
npm install fails to install bcrypt because of missing python executable

### ISSUE THREAD

**Issue by FrankDhondt** [dimitrydhondt/inner-gerbil#42]
C:\Git\inner-gerbil>npm install
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
|

> bcrypt@0.8.5 install C:\Git\inner-gerbil\node_modules\bcrypt
> node-gyp rebuild

)  else (rebuild)
gyp ERR! configure error modules\bcrypt>if not defined npm_config_node_gyp (node "gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.yp.js" rebuild
ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Git\inner-gerbil\node_modules\bcrypt
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN prefer global jake@8.0.12 should be installed with -g
npm WARN optional dep failed, continuing fsevents@1.0.6
npm WARN prefer global nodemon@1.7.0 should be installed with -g
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Git\inner-gerbil\npm-debug.log

**Comment by dimitrydhondt** [comment]
Cloud9 is gratis, en biedt genoeg RAM en DISK voor gerbil...
Dimi

Verzonden via Yahoo Mail op Android 
 
  Op zo, jan. 31, 2016 om 10:14 schreef FrankDhondt<notifications@github.com>:   
C:\Git\inner-gerbil>npm install
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
|


bcrypt@0.8.5 install C:\Git\inner-gerbil\node_modules\bcrypt
node-gyp rebuild


) else (rebuild)
gyp ERR! configure error modules\bcrypt>if not defined npm_config_node_gyp (node "gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.yp.js" rebuild
ERR! stack at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack at FSReqWrap.oncomplete (evalmachine.:95:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Git\inner-gerbil\node_modules\bcrypt
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN prefer global jake@8.0.12 should be installed with -g
npm WARN optional dep failed, continuing fsevents@1.0.6
npm WARN prefer global nodemon@1.7.0 should be installed with -g
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Git\inner-gerbil\npm-debug.log

**Comment by dimitrydhondt** [comment]
Just double-checked it and you get 1GB of RAM and 5GB of disk space. Ample for development on inner/arty/nosy-gerbil :-)

Just create a folder per project in your workspace, and you'll be good to go anywhere with a browser and a decent internet connection...

Plus the install and dependencies are all scripted, and work right out of the box. Just run `./install-cloud9.sh` after cloning from github.

If you like eslint support right in the editor, copy the .eslintrc into the root workspace folder.

I can share debugging configurations as well, to debug mocha tests and the server itself.

Dimi
